module.exports = class UserDto {
  id;
  name;
  email;
  phone_number;
  avatar;
  role;
  bio;
  location;
  joinedAt;
  createdAt;
  language;
  socials;
  visitedPlaces;
  savedPlaces;
  comments;
  settings;
  isActive;
  emailVerified;
  isGit;
  stats;
  myPlaces;
  notifications;

  constructor(user) {
    const obj = user || {};
    this.id = obj._id ? String(obj._id) : (obj.id ? String(obj.id) : undefined);
    this.name = obj.name;
    this.email = obj.email;
    this.phone_number = obj.phone_number;
    this.avatar = obj.avatar;
    this.role = obj.role;
    this.bio = obj.bio || "";
    this.location = obj.location || "";
    this.joinedAt = obj.joinedAt;
    this.createdAt = obj.createdAt;
    this.language = obj.settings?.language || obj.language || "uz";
    this.socials = obj.socials || {};
    this.visitedPlaces = obj.visitedPlaces || [];
    this.savedPlaces = obj.savedPlaces || [];
    this.comments = obj.comments || [];
    this.settings = obj.settings;
    this.isActive = Boolean(obj.isActive);
    this.emailVerified = Boolean(obj.emailVerified);
    this.isGit = Boolean(obj.isGit);
    this.stats = obj.stats || {};
    this.myPlaces = obj.myPlaces || [];
    this.notifications = obj.notifications || [];
  }
};
